[build]
  functions = "netlify/edge-functions"

[[edge_functions]]
  path = "/api/save"
  function = "save"

[[edge_functions]]
  path = "/api/list"
  function = "list"

[[edge_functions]]
  path = "/api/read"
  function = "read"
